version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: tenantforge-pg-test
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tenantforge
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgtest-data:/var/lib/postgresql/data
volumes:
  pgtest-data:

