version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tenantforge
      POSTGRES_USER: tenantforge
      POSTGRES_PASSWORD: tenantforge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tenantforge
      SPRING_DATASOURCE_USERNAME: tenantforge
      SPRING_DATASOURCE_PASSWORD: tenantforge
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata: {}
