spring:
  application:
    name: tenantforge-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tenantforge}
    username: ${SPRING_DATASOURCE_USERNAME:tenantforge}
    password: ${SPRING_DATASOURCE_PASSWORD:tenantforge}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    tags:
      application: tenantforge-backend

logging:
  level:
    root: INFO
    org.springframework.security: INFO

app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-change-me-change-me-change-me-123456}
      issuer: tenantforge
      access-token-ttl: ${JWT_ACCESS_TTL:PT15M}
      refresh-token-ttl: ${JWT_REFRESH_TTL:PT168H}
